project:
  type: website
  pre-render: R/preRender.R
  render:
    - "*.qmd"

website:
  title: "rvc_percent_cover"
  navbar:
    left:
      - href: index.qmd
        text: Home
        aoi_report/aoi_reports.qmd
      - #about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



